name: Shopping
main: fr.chklang.minecraft.shoping.Main
version: 0.0.1-SNAPSHOT
author: Chklang
database: true
depend: [Vault, SQLibrary]
commands:
   shopping:
      description: This is the main command for shopping.
      usage: /shopping [player]
   shopping.create:
      description: Create a new shop
      usage: /shopping.create
      permission: shopping.create
      permission-message: You can't create a new shop
   shopping.setcorner:
      description: Set one of three corners for a shop
      usage: /shopping.setcorner [idshop] [?idcorner]
      permission: shopping.create
      permission-message: You can't create/modify a shop
permissions:
   shopping.*:
      description: Gives access to all shopping commands
      children:
         shopping.create: true
   shopping.create:
      description: Create and modify shops
      default: true